# This is a basic workflow to help you get started with Actions

name: React App deploy to surge 

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Installs node JS
    - name: Install nodeJS
      uses: actions/setup-node@v2-beta
      with:
        version: 12 
      
    - name: Installs react, react-dom, react-scripts
      run: npm install react react-dom react-scripts 
    
    - name: Build React App
      run: npm run build
    
    - name: Install surge
      run: npm install --global surge
    
    - name: Deploy to surge
      run: surge ./build testing-surge-deploy-github-actions.surge.sh --token ${{ secrets.SURGE_TOKEN }}
